habitproject/habitapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='habitapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('update_habit/<int:habit_id>', views.update_habit, name='update_habit'),
    path('delete/', views.delete, name='delete'),
]

habitproject/habitproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('habitapp/', include('habitapp.urls')),
]

habitproject/habitapp/models.py
from django.db import models

class Habit(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    goal = models.IntegerField(default=0, null=False)
    monday = models.BooleanField(default=False, null=False)
    tuesday = models.BooleanField(default=False, null=False)
    wednesday = models.BooleanField(default=False, null=False)
    thursday = models.BooleanField(default=False, null=False)
    friday = models.BooleanField(default=False, null=False)
    saturday = models.BooleanField(default=False, null=False)
    sunday = models.BooleanField(default=False, null=False)
    progress = models.IntegerField(default=0, null=False)

    def __str__(self):
        return f'{self.name} {self.description} {self.goal}'

class Deleted(models.Model):
    deleted = models.BooleanField(default=False, null=False)

habitproject/habitapp/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import Habit, Deleted
    
def index(request):
    habits = Habit.objects.all()
    loeschen = Deleted.objects.all()
    for habit in habits:
        habit.progress = summe_berechnen(habit)
        habit.save()
    for entry in loeschen:
        if datetime.today().weekday() == 0 and entry.deleted == False:
            delete_monday()
            entry.deleted = True
            entry.save()
        if datetime.today().weekday() != 0 and entry.deleted == True:
            entry.deleted = False
            entry.save()
    return render(request, 'habitapp/index.html', {'habits': habits})

def delete_monday():
    habits = Habit.objects.all()
    for habit in habits:
        habit.monday = False
        habit.tuesday = False
        habit.wednesday = False
        habit.thursday = False
        habit.friday = False
        habit.saturday = False
        habit.sunday = False
        habit.progress = 0
        habit.save()

def delete(request):
    habits = Habit.objects.all()
    for habit in habits:
        habit.monday = False
        habit.tuesday = False
        habit.wednesday = False
        habit.thursday = False
        habit.friday = False
        habit.saturday = False
        habit.sunday = False
        habit.progress = 0
        habit.save()
    context = {
        'habits': habits, 
    }
    return render(request, 'habitapp/index.html', context)

def summe_berechnen(habit):
    summe = 0
    if habit.monday:
        summe += 1
    if habit.tuesday:
        summe += 1
    if habit.wednesday:
        summe += 1
    if habit.thursday:
        summe += 1
    if habit.friday:
        summe += 1
    if habit.saturday:
        summe += 1
    if habit.sunday:
        summe += 1
    return summe

def update_habit_def(habit, post):
    habit.monday = "habit.monday" in post
    habit.tuesday = "habit.tuesday" in post
    habit.wednesday = "habit.wednesday" in post
    habit.thursday = "habit.thursday" in post
    habit.friday = "habit.friday" in post
    habit.saturday = "habit.saturday" in post
    habit.sunday = "habit.sunday" in post
    habit.save()


def update_habit(request, habit_id):
    habit = get_object_or_404(Habit, pk=habit_id)
    if request.POST:
        update_habit_def(habit, request.POST)
        return HttpResponseRedirect(reverse('habitapp:index'))
    context = {
            "habit": habit, 
            }
    return render(request, "habitapp/index.html", context)

habitproject/habitapp/templates/habitapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Startseite</title>
</head>
<body>
    
    <table class='table'>
        <tr>
            <th>Habit</th><th>Beschreibung</th><th>Montag</th><th>Dienstag</th><th>Mittwoch</th><th>Donnerstag</th><th>Freitag</th><th>Samstag</th><th>Sonntag</th><th>Summe</th><th>Speichern</th>
        </tr>
        {% for habit in habits %}
            <tr>
                <td class='p-3'>{{habit.name}}</td>
                <td class='p-3'>{{habit.description}}</td>
                <form action="{% url 'habitapp:update_habit' habit.id %}" method="POST">
                    {% csrf_token %}
                <td>
                    <input type="checkbox" name="habit.monday" {% if habit.monday %}checked{% endif %}>
                </td>
                <td>
                    <input type="checkbox" name="habit.tuesday" {% if habit.tuesday %}checked{% endif %}>
                </td>
                <td>
                    <input type="checkbox" name="habit.wednesday" {% if habit.wednesday %}checked{% endif %}>
                </td>
                <td>
                    <input type="checkbox" name="habit.thursday" {% if habit.thursday %}checked{% endif %}>
                </td>
                <td>
                    <input type="checkbox" name="habit.friday" {% if habit.friday %}checked{% endif %}>
                </td>
                <td>
                    <input type="checkbox" name="habit.saturday" {% if habit.saturday %}checked{% endif %}>
                </td>
                <td>
                    <input type="checkbox" name="habit.sunday" {% if habit.sunday %}checked{% endif %}>
                </td>
                <td>{{habit.progress}}/{{habit.goal}}</td>
                <td>
                    <div class="input-group">
                        <input class="btn" type="submit" value="Speichern">
                    </div>
                </td>
            </form>
                    
            </tr>
        {% endfor %}
    </table>

    Vergessen am Montag zu löschen?</br>
    <a href="{% url 'habitapp:delete'%}">Löschen</a>

</body>
</html>